### ISSUE TITLE
Leaflet 0.4.5

### ISSUE THREAD

**Issue by ZJONSSON** [sztanko/crosslet#1]
There is an annoying bug in leaflet 0.4.4 (and older) when zooming with Chrome (animation is wobbly).  You might consider pointing the examples to: 
http://cdn.leafletjs.com/leaflet-0.4.5/leaflet.js
See https://github.com/Leaflet/Leaflet/issues/1056

**Comment by sztanko** [comment]
Thanks for noticing that! Will fix soon.

**Comment by sztanko** [comment]
Done & thank you.
